library(shiny)
shinyUI(fluidPage(
    titlePanel("Conversion Rates between the Euro and European Monetary
            Union (EMU) Currencies adopted on December 31, 1998"),
        sidebarLayout(
          sidebarPanel(
          sliderInput("sliderEuros", "How many Units?", 1,100, value=1),
          submitButton("Submit")
          ),
        mainPanel(
##         img(src='slider.PNG'),
##             align = "right"),
##         img(scr='/Users/patri/Documents/2020_backup/Documents/p/USB Drive/
##                DSC_0016.jpg',
                    
                tabsetPanel(
                    type="tabs",
                tabPanel("EURO to EMU", br(),plotOutput("plot1"),
##                       h5("ATS: Austrian Schilling"),
                         h5(textOutput("curr1")),
##                       h5("BEF: Belgian Franc"),
                         h5(textOutput("curr2")),
##                       h5("DEM: German Mark"),
                         h5(textOutput("curr3")),
##                       h5("ESP: Spanish Peseta"),
                         h5(textOutput("curr4")),
##                       h5("Finnish Markka FIM"),
                         h5(textOutput("curr5")),
##                       h5("FRF: French Franc"),
                         h5(textOutput("curr6")),
##                       h5("IEP: Irish Punt"),
                         h5(textOutput("curr7")),
##                       h5("ITL: Italian Lira ITL"),
                         h5(textOutput("curr8")),
##                       h5("LUF: Luxembourg Franc"),
                         h5(textOutput("curr9")),
##                       h5("NLG: Dutch Guilder"),
                         h5(textOutput("curr10")),
##                       h5("PTE: Portuguese Escudo"),
                         h5(textOutput("curr11"))),
##                       h5("PTE: Portuguese Escudo")),
##                       textOutput("curr11"),
                tabPanel("EMU TO EURO", br(), plotOutput("plot2"),
##                        h5("ATS: Austrian Schilling"),
                         h5(textOutput("euro1")),
##                       h5("BEF: Belgian Franc"),
                         h5(textOutput("euro2")),
##                       h5("DEM: German Mark"),
                         h5(textOutput("euro3")),
##                       h5("ESP: Spanish Peseta"),
                         h5(textOutput("euro4")),
##                       h5("Finnish Markka FIM"),
                         h5(textOutput("euro5")),
##                       h5("FRF: French Franc"),
                         h5(textOutput("euro6")),
##                       h5("IEP: Irish Punt"),
                         h5(textOutput("euro7")),
##                       h5("ITL: Italian Lira ITL"),
                         h5(textOutput("euro8")),
##                       h5("LUF: Luxembourg Franc"),
                         h5(textOutput("euro9")),
##                       h5("NLG: Dutch Guilder"),
                         h5(textOutput("euro10")),
##                       h5("PTE: Portuguese Escudo"),
                         h5(textOutput("euro11"))),
                tabPanel("Documentation", br(), 
                         h4(textOutput("doc1")),
                         textOutput("doc2"),
                         textOutput("doc3"),
                         textOutput("doc4"),
                         p(textOutput("doc5")),
                         textOutput("doc5a"),
                         textOutput("doc5b"),
                         h4(textOutput("doc6")),
                         textOutput("doc7"),
                         textOutput("doc8"),
                         textOutput("doc9"),
                         p(textOutput("doc10")),
                         textOutput("doc10a"),
                         textOutput("doc10b"))
              )
        )
    )
))